import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const MORE_SPOTS = [
  { name: "Bedok Public Library", slug: "bedok-public-library", category: "NLB_LIBRARY" as const, address: "11 Bedok North Street 1, Singapore 469662", postalCode: "469662", lat: 1.3236, lng: 103.9304, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 80, groupStudy: false, soloStudy: true, privateRooms: 2, nearestMrt: "Bedok", mrtWalkMins: 5, isVerified: true, tags: ["eastern"] },
  { name: "Bukit Batok Public Library", slug: "bukit-batok-public-library", category: "NLB_LIBRARY" as const, address: "1 Bukit Batok Central Link, Singapore 658713", postalCode: "658713", lat: 1.3491, lng: 103.7493, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 60, groupStudy: false, soloStudy: true, privateRooms: 2, nearestMrt: "Bukit Batok", mrtWalkMins: 3, isVerified: true, tags: ["western"] },
  { name: "Clementi Public Library", slug: "clementi-public-library", category: "NLB_LIBRARY" as const, address: "3155 Commonwealth Avenue West, Singapore 129588", postalCode: "129588", lat: 1.3153, lng: 103.7650, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 70, groupStudy: true, soloStudy: true, privateRooms: 3, nearestMrt: "Clementi", mrtWalkMins: 4, isVerified: true, tags: ["western", "nus-nearby"] },
  { name: "library@harbourfront", slug: "library-harbourfront", category: "NLB_LIBRARY" as const, address: "1 HarbourFront Walk, VivoCity #01-K8, Singapore 098585", postalCode: "098585", lat: 1.2645, lng: 103.8200, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 50, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "HarbourFront", mrtWalkMins: 2, isVerified: true, tags: ["vivocity", "southern"] },
  { name: "library@orchard", slug: "library-orchard", category: "NLB_LIBRARY" as const, address: "277 Orchard Road, Orchard Gateway #03-12, Singapore 238858", postalCode: "238858", lat: 1.3008, lng: 103.8392, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 60, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Somerset", mrtWalkMins: 2, isVerified: true, tags: ["orchard", "central"] },
  { name: "Queenstown Public Library", slug: "queenstown-public-library", category: "NLB_LIBRARY" as const, address: "53 Margaret Drive, Singapore 149297", postalCode: "149297", lat: 1.2952, lng: 103.7988, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 60, groupStudy: false, soloStudy: true, privateRooms: 2, nearestMrt: "Queenstown", mrtWalkMins: 8, isVerified: true, tags: ["central-west"] },
  { name: "Serangoon Public Library", slug: "serangoon-public-library", category: "NLB_LIBRARY" as const, address: "23 Serangoon Central, NEX #03-26, Singapore 556083", postalCode: "556083", lat: 1.3498, lng: 103.8731, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 70, groupStudy: false, soloStudy: true, privateRooms: 2, nearestMrt: "Serangoon", mrtWalkMins: 2, isVerified: true, tags: ["northeast", "nex"] },
  { name: "Toa Payoh Public Library", slug: "toa-payoh-public-library", category: "NLB_LIBRARY" as const, address: "6 Toa Payoh Central, Singapore 319191", postalCode: "319191", lat: 1.3326, lng: 103.8468, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 80, groupStudy: false, soloStudy: true, privateRooms: 2, nearestMrt: "Toa Payoh", mrtWalkMins: 5, isVerified: true, tags: ["central"] },
  { name: "NTU Library", slug: "ntu-library", category: "UNIVERSITY_LIBRARY" as const, address: "50 Nanyang Avenue, Singapore 639798", postalCode: "639798", lat: 1.3483, lng: 103.6831, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 350, groupStudy: true, soloStudy: true, privateRooms: 12, nearestMrt: "Boon Lay", mrtWalkMins: 20, isVerified: true, tags: ["ntu", "university", "western"] },
  { name: "SIT@NYP Study Hub", slug: "sit-nyp-study-hub", category: "UNIVERSITY_LIBRARY" as const, address: "180 Ang Mo Kio Avenue 8, Singapore 569830", postalCode: "569830", lat: 1.3698, lng: 103.8487, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 120, groupStudy: true, soloStudy: true, privateRooms: 4, nearestMrt: "Ang Mo Kio", mrtWalkMins: 10, isVerified: true, tags: ["sit", "nyp", "polytechnic"] },
  { name: "Republic Polytechnic Library", slug: "republic-polytechnic-library", category: "UNIVERSITY_LIBRARY" as const, address: "9 Woodlands Avenue 9, Singapore 738964", postalCode: "738964", lat: 1.4389, lng: 103.7820, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 200, groupStudy: true, soloStudy: true, privateRooms: 8, nearestMrt: "Woodlands", mrtWalkMins: 15, isVerified: true, tags: ["rp", "polytechnic", "northern"] },
  { name: "Nanyang Polytechnic Library", slug: "nanyang-polytechnic-library", category: "UNIVERSITY_LIBRARY" as const, address: "180 Ang Mo Kio Avenue 8, Singapore 569830", postalCode: "569830", lat: 1.3694, lng: 103.8481, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 250, groupStudy: true, soloStudy: true, privateRooms: 10, nearestMrt: "Ang Mo Kio", mrtWalkMins: 12, isVerified: true, tags: ["nyp", "polytechnic"] },
  { name: "Temasek Polytechnic Library", slug: "temasek-polytechnic-library", category: "UNIVERSITY_LIBRARY" as const, address: "21 Tampines Avenue 1, Singapore 529757", postalCode: "529757", lat: 1.3453, lng: 103.9324, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 220, groupStudy: true, soloStudy: true, privateRooms: 8, nearestMrt: "Tampines", mrtWalkMins: 18, isVerified: true, tags: ["tp", "polytechnic", "eastern"] },
  { name: "Singapore Polytechnic Library", slug: "singapore-polytechnic-library", category: "UNIVERSITY_LIBRARY" as const, address: "500 Dover Road, Singapore 139651", postalCode: "139651", lat: 1.3100, lng: 103.7780, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 200, groupStudy: true, soloStudy: true, privateRooms: 8, nearestMrt: "Dover", mrtWalkMins: 5, isVerified: true, tags: ["sp", "polytechnic"] },
  { name: "The Coffee Bean & Tea Leaf (Novena Square)", slug: "cbtl-novena", category: "CAFE" as const, address: "238 Thomson Road, Novena Square, Singapore 307683", postalCode: "307683", lat: 1.3201, lng: 103.8442, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: false, totalSeats: 40, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Novena", mrtWalkMins: 3, isVerified: true, tags: ["cafe", "laptop-friendly"] },
  { name: "Starbucks (Tampines Mall)", slug: "starbucks-tampines", category: "CAFE" as const, address: "4 Tampines Central 5, Singapore 529510", postalCode: "529510", lat: 1.3527, lng: 103.9453, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: false, totalSeats: 50, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Tampines", mrtWalkMins: 3, isVerified: true, tags: ["cafe", "eastern"] },
  { name: "Starbucks (Jurong Point)", slug: "starbucks-jurong-point", category: "CAFE" as const, address: "1 Jurong West Central 2, Singapore 648886", postalCode: "648886", lat: 1.3401, lng: 103.7063, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: false, totalSeats: 45, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Boon Lay", mrtWalkMins: 5, isVerified: true, tags: ["cafe", "western"] },
  { name: "Toast Box (Bedok Mall)", slug: "toast-box-bedok", category: "CAFE" as const, address: "311 New Upper Changi Road, Singapore 467360", postalCode: "467360", lat: 1.3240, lng: 103.9290, hasWifi: true, hasPowerSockets: false, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: false, totalSeats: 60, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Bedok", mrtWalkMins: 3, isVerified: true, tags: ["cafe", "eastern", "budget"] },
  { name: "Koi Cafe (Toa Payoh)", slug: "koi-toa-payoh", category: "CAFE" as const, address: "190 Lorong 6 Toa Payoh, Singapore 310190", postalCode: "310190", lat: 1.3352, lng: 103.8481, hasWifi: true, hasPowerSockets: false, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: false, totalSeats: 35, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Toa Payoh", mrtWalkMins: 5, isVerified: true, tags: ["cafe", "central"] },
  { name: "Windowsill Pies (Clementi)", slug: "windowsill-pies-clementi", category: "CAFE" as const, address: "451 Clementi Avenue 3, Singapore 120451", postalCode: "120451", lat: 1.3141, lng: 103.7659, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: false, totalSeats: 30, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Clementi", mrtWalkMins: 8, isVerified: true, tags: ["cafe", "quiet", "western", "nus-nearby"] },
  { name: "McDonald's Changi Airport T2 24h", slug: "mcdonalds-changi-t2", category: "MCDONALDS_24H" as const, address: "60 Airport Boulevard, T2 #B2-01, Singapore 819643", postalCode: "819643", lat: 1.3592, lng: 103.9896, hasWifi: true, hasPowerSockets: false, isAirCon: true, noiseLevel: "LIVELY" as const, is24Hours: true, requiresBooking: false, isFree: false, totalSeats: 150, groupStudy: true, soloStudy: true, privateRooms: 0, nearestMrt: "Changi Airport", mrtWalkMins: 5, isVerified: true, tags: ["24h", "late-night", "airport"] },
  { name: "McDonald's Tampines 24h", slug: "mcdonalds-tampines-24h", category: "MCDONALDS_24H" as const, address: "10 Tampines Central 1, Singapore 529536", postalCode: "529536", lat: 1.3530, lng: 103.9440, hasWifi: true, hasPowerSockets: false, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: true, requiresBooking: false, isFree: false, totalSeats: 100, groupStudy: true, soloStudy: true, privateRooms: 0, nearestMrt: "Tampines", mrtWalkMins: 3, isVerified: true, tags: ["24h", "late-night", "eastern"] },
  { name: "McDonald's Woodlands 24h", slug: "mcdonalds-woodlands-24h", category: "MCDONALDS_24H" as const, address: "900 South Woodlands Drive, Singapore 730900", postalCode: "730900", lat: 1.4368, lng: 103.7860, hasWifi: true, hasPowerSockets: false, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: true, requiresBooking: false, isFree: false, totalSeats: 90, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Woodlands", mrtWalkMins: 5, isVerified: true, tags: ["24h", "late-night", "northern"] },
  { name: "McDonald's Clementi 24h", slug: "mcdonalds-clementi-24h", category: "MCDONALDS_24H" as const, address: "3155 Commonwealth Avenue West, Singapore 129588", postalCode: "129588", lat: 1.3155, lng: 103.7651, hasWifi: true, hasPowerSockets: false, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: true, requiresBooking: false, isFree: false, totalSeats: 80, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Clementi", mrtWalkMins: 4, isVerified: true, tags: ["24h", "late-night", "western", "nus-nearby"] },
  { name: "JustCo (Robinson Road)", slug: "justco-robinson", category: "COWORKING" as const, address: "77 Robinson Road, Singapore 068896", postalCode: "068896", lat: 1.2797, lng: 103.8489, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: true, isFree: false, pricePerHour: 8, totalSeats: 150, groupStudy: true, soloStudy: true, privateRooms: 6, nearestMrt: "Tanjong Pagar", mrtWalkMins: 5, isVerified: true, tags: ["coworking", "cbd"] },
  { name: "WeWork (Beach Road)", slug: "wework-beach-road", category: "COWORKING" as const, address: "181 Beach Road, Singapore 189763", postalCode: "189763", lat: 1.2990, lng: 103.8601, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: true, isFree: false, pricePerHour: 10, totalSeats: 200, groupStudy: true, soloStudy: true, privateRooms: 10, nearestMrt: "Bugis", mrtWalkMins: 8, isVerified: true, tags: ["coworking", "city"] },
  { name: "Tampines West CC Study Room", slug: "tampines-west-cc", category: "COMMUNITY_CENTER" as const, address: "10 Tampines Street 81, Singapore 528708", postalCode: "528708", lat: 1.3478, lng: 103.9276, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 40, groupStudy: false, soloStudy: true, privateRooms: 1, nearestMrt: "Tampines West", mrtWalkMins: 10, isVerified: true, tags: ["community", "free", "eastern"] },
  { name: "Woodlands CC Study Corner", slug: "woodlands-cc", category: "COMMUNITY_CENTER" as const, address: "1 Woodlands Street 81, Singapore 738526", postalCode: "738526", lat: 1.4319, lng: 103.7862, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 35, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Woodlands", mrtWalkMins: 12, isVerified: true, tags: ["community", "free", "northern"] },
  { name: "Jurong West CC Study Room", slug: "jurong-west-cc", category: "COMMUNITY_CENTER" as const, address: "20 Jurong West Street 93, Singapore 648965", postalCode: "648965", lat: 1.3479, lng: 103.6980, hasWifi: true, hasPowerSockets: false, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 30, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Boon Lay", mrtWalkMins: 20, isVerified: true, tags: ["community", "free", "western"] },
  { name: "Punggol Regional Library (Upcoming)", slug: "punggol-regional-library", category: "NLB_LIBRARY" as const, address: "1 Punggol Drive, Singapore 828629", postalCode: "828629", lat: 1.4041, lng: 103.9022, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 100, groupStudy: true, soloStudy: true, privateRooms: 4, nearestMrt: "Punggol", mrtWalkMins: 8, isVerified: false, tags: ["northeast", "punggol"] },
  { name: "Sengkang Public Library", slug: "sengkang-public-library", category: "NLB_LIBRARY" as const, address: "1 Sengkang Square, Compass One #03-01, Singapore 545078", postalCode: "545078", lat: 1.3917, lng: 103.8953, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 80, groupStudy: false, soloStudy: true, privateRooms: 2, nearestMrt: "Sengkang", mrtWalkMins: 2, isVerified: true, tags: ["northeast", "compass-one"] },
  { name: "Hougang Public Library", slug: "hougang-public-library", category: "NLB_LIBRARY" as const, address: "21 Hougang Street 51, Heartland Mall, Singapore 538719", postalCode: "538719", lat: 1.3719, lng: 103.8930, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 70, groupStudy: false, soloStudy: true, privateRooms: 2, nearestMrt: "Hougang", mrtWalkMins: 5, isVerified: true, tags: ["northeast"] },
  { name: "Pasir Ris Public Library", slug: "pasir-ris-public-library", category: "NLB_LIBRARY" as const, address: "1 Pasir Ris Central Street 3, White Sands, Singapore 518457", postalCode: "518457", lat: 1.3728, lng: 103.9494, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 70, groupStudy: false, soloStudy: true, privateRooms: 2, nearestMrt: "Pasir Ris", mrtWalkMins: 4, isVerified: true, tags: ["eastern", "white-sands"] },
  { name: "National Museum Reading Room", slug: "national-museum-reading-room", category: "OTHER" as const, address: "93 Stamford Road, Singapore 178897", postalCode: "178897", lat: 1.2966, lng: 103.8484, hasWifi: true, hasPowerSockets: false, isAirCon: true, noiseLevel: "SILENT" as const, is24Hours: false, requiresBooking: false, isFree: false, totalSeats: 30, groupStudy: false, soloStudy: true, privateRooms: 0, nearestMrt: "Bras Basah", mrtWalkMins: 5, isVerified: true, tags: ["museum", "silent", "heritage"] },
  { name: "Ngee Ann Polytechnic Library", slug: "ngee-ann-polytechnic-library", category: "UNIVERSITY_LIBRARY" as const, address: "535 Clementi Road, Singapore 599489", postalCode: "599489", lat: 1.3331, lng: 103.7757, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: false, isFree: true, totalSeats: 300, groupStudy: true, soloStudy: true, privateRooms: 10, nearestMrt: "Buona Vista", mrtWalkMins: 15, isVerified: true, tags: ["np", "polytechnic", "western"] },
  { name: "Koufu Food Court (Bedok Point)", slug: "koufu-bedok-point", category: "HAWKER_CENTER" as const, address: "799 New Upper Changi Road, Singapore 467351", postalCode: "467351", lat: 1.3244, lng: 103.9302, hasWifi: false, hasPowerSockets: false, isAirCon: false, noiseLevel: "LIVELY" as const, is24Hours: false, requiresBooking: false, isFree: false, totalSeats: 200, groupStudy: true, soloStudy: true, privateRooms: 0, nearestMrt: "Bedok", mrtWalkMins: 5, isVerified: true, tags: ["hawker", "budget", "eastern"] },
  { name: "Maxwell Food Centre", slug: "maxwell-food-centre", category: "HAWKER_CENTER" as const, address: "1 Kadayanallur Street, Singapore 069184", postalCode: "069184", lat: 1.2803, lng: 103.8456, hasWifi: false, hasPowerSockets: false, isAirCon: false, noiseLevel: "LIVELY" as const, is24Hours: false, requiresBooking: false, isFree: false, totalSeats: 300, groupStudy: true, soloStudy: true, privateRooms: 0, nearestMrt: "Tanjong Pagar", mrtWalkMins: 5, isVerified: true, tags: ["hawker", "budget", "cbd", "chinatown"] },
  { name: "The Hive Lavender", slug: "hive-lavender", category: "COWORKING" as const, address: "32 Carpenter Street, Singapore 059911", postalCode: "059911", lat: 1.2871, lng: 103.8454, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "MODERATE" as const, is24Hours: false, requiresBooking: true, isFree: false, pricePerHour: 5, totalSeats: 80, groupStudy: true, soloStudy: true, privateRooms: 4, nearestMrt: "Clarke Quay", mrtWalkMins: 8, isVerified: true, tags: ["coworking", "affordable"] },
  { name: "NUSS Kent Ridge Guild House", slug: "nuss-kent-ridge", category: "COWORKING" as const, address: "9 Kent Ridge Drive, Singapore 119241", postalCode: "119241", lat: 1.2937, lng: 103.7818, hasWifi: true, hasPowerSockets: true, isAirCon: true, noiseLevel: "QUIET" as const, is24Hours: false, requiresBooking: false, isFree: false, totalSeats: 60, groupStudy: true, soloStudy: true, privateRooms: 2, nearestMrt: "Kent Ridge", mrtWalkMins: 5, isVerified: true, tags: ["nus-nearby", "quiet", "western"] },
];

async function main() {
  console.log("🌱 Adding more study spots...");
  let created = 0, skipped = 0;

  for (const spot of MORE_SPOTS) {
    try {
      const existing = await prisma.studySpot.findUnique({ where: { slug: spot.slug } });
      if (existing) { skipped++; continue; }

      await prisma.studySpot.create({
        data: {
          ...spot,
          dataSource: "manual",
          openingHours: {
            create: [
              { dayOfWeek: 0, openTime: "10:00", closeTime: "21:00" },
              { dayOfWeek: 1, openTime: "09:00", closeTime: "21:00" },
              { dayOfWeek: 2, openTime: "09:00", closeTime: "21:00" },
              { dayOfWeek: 3, openTime: "09:00", closeTime: "21:00" },
              { dayOfWeek: 4, openTime: "09:00", closeTime: "21:00" },
              { dayOfWeek: 5, openTime: "09:00", closeTime: "21:00" },
              { dayOfWeek: 6, openTime: "10:00", closeTime: "21:00" },
            ],
          },
        },
      });
      console.log(`  ✅ ${spot.name}`);
      created++;
    } catch (err) {
      console.error(`  ❌ ${spot.name}`, err);
    }
  }
  console.log(`\n✨ Done! Created: ${created}, Skipped: ${skipped}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());